config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get 'main/today_birthday'
  get 'main/wish_birthday'
  post 'main/viewall'
  devise_for :users, :controllers => {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
	  @users = User.all
  end
  def viewall
		user = User.all
		render :json => user
  end
  def today_birthday
		@user = User.all
    @user_array = Array.new
    @user.each do |user|
      user_hash = Hash.new
      if Date.today.strftime("%d-%m") == user.dob.strftime("%d-%m")
        user_hash[:id] = user.id
        user_hash[:firstname] = user.firstname
        user_hash[:lastname] = user.lastname
        user_hash[:email] = user.email
        user_hash[:dob] = user.dob
        @user_array.push(user_hash)
      end
    end
  end
  def wish_birthday
    @user = User.find(params[:id])
  	UserMailer.birthday_wish(@user, current_user).deliver_now
    redirect_to main_today_birthday_url, :notice => "Birthday Mail Sent!"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def sign_up_params
    params.require(:user).permit(:email,:password,:password_confirmation,:firstname,:lastname,:dob,:address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue">
<div id="footer">
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</div>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box;}

body { 
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.header {
  overflow: hidden;
  background-color: #007bff;
  padding: 10px 10px;
}

.header a {
  float: left;
  color: black;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 18px; 
  line-height: 25px;
  border-radius: 4px;
}

.header a.logo {
  font-size: 25px;
  font-weight: bold;
}

.header a:hover {
  background-color: #ddd;
  color: black;
}

.header a.active {
  background-color: dodgerblue;
  color: white;
}

.header-right {
  float: right;
}

@media screen and (max-width: 500px) {
  .header a {
    float: none;
    display: block;
    text-align: left;
  }
  
  .header-right {
    float: none;
  }
}
</style>
</head>
<body>

<div class="header">
  <a href="#default" class="logo">BirthdayWish</a>
  <div class="header-right">
    <%if !user_signed_in?%>
      <p class="active"><%= link_to "Home", root_path%><%= link_to "Sign_In", new_user_session_path%><%= link_to "Sign_Up", new_user_registration_path%></p>

    <% end %>
    <%if user_signed_in?%>
      <p class="sign_out"><%= link_to "Home", root_path%><%= link_to "Sign_Out", destroy_user_session_path, :method => :delete %></p> 
    <% end %>
  </div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Birthdaywish</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/main/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <div>
    <%if current_user%>
      <%= button_tag "View Today's birthday",:onclick => "location.href = 'main/today_birthday'", class: 'btn btn-default' %>
    <%end%> 
    <%if !current_user%>
      <p>please sign-in for wishing birthday</p>
    <%end%> 
  </div>

  <title></title>
</head>
<body>
<h3>All User Birthday </h3>
<table>                         
  <tr>                          
    <th> First Name</th>
    <th>Last Name</th>
    <th> Email</th>
    <th>Birthdate</th>

  </tr>
  <% @users.each do |data| %>      
    <tr>
      <td><%= data.firstname %></td>  
      <td><%= data.lastname %></td>
      <td><%= data.email %></td>
      <% if data.dob.present?%>  
      <td><%= data.dob.strftime("%d/%m/%Y") %></td>
      <%end%>
    </tr>
  <% end %>
</table>       
</body>
</html>

app/views/main/today_birthday.html.erb
<%= link_to 'Back', root_path%>

<h3>List of today's birthday</h3>

<table>                         
  <tr>                          
    <th> First Name</th>
    <th>Last Name</th>
    <th> Email</th>
    <th>Birthdate</th>
    <th>Wish</th>
  </tr>
  <% @user_array.each do |data| %>      
  <tr>
    <td><%= data[:firstname] %></td>  
    <td><%= data[:lastname] %></td>
    <td><%= data[:email] %></td>  
    <td><%= data[:dob].strftime("%d/%m/%Y") %></td>
    <td><%= link_to 'Wish Birthday', main_wish_birthday_path(id:data[:id], current_user: current_user)%></td>  
  </tr>
  <% end %>
</table>